services:
  techmely-web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # make sure this directory has the same ownership as the techmely-web user from the Dockerfile
      # otherwise Elk will not be able to store configs for accounts
      # e.q. mkdir ./techmely-web-storage; sudo chown 911:911 ./techmely-web-storage
      - './docker-storage:/techmely/web/data'
    ports:
      - 2023:2023
