name: startly
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - "registry.gitlab.com/techmely/starly:0.0.1"
    ports:
      - "${PORT}:${PORT}"
    healthcheck:
      test: "curl -f http://localhost:${PORT}"
      interval: 5s
      timeout: 5s
      retries: 40
