name: ddd_core
description: Dart package which manages http_client.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  another_flushbar: ^1.12.30
  calendar_time: ^2.2.0
  collection: ^1.18.0
  cyclop: ^0.7.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.5
  formz: ^0.7.0
  freezed_annotation: ^2.2.0
  equatable: ^2.0.5
  hive: ^2.2.3
  injectable: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
