version: "3.8"
name: techmely-local-db
services:
  postgresql:
    image: docker.io/bitnami/postgresql:16.3.0
    ports:
      - "5432:5432"
    volumes:
      - "postgresql_data:/bitnami/postgresql"
    environment:
      - POSTGRESQL_USERNAME=techmely_hyperdrive
      - POSTGRESQL_DATABASE=techmely
      - POSTGRESQL_PASSWORD=techmely_password
  minio:
    image: bitnami/minio:latest
    environment:
      - MINIO_ROOT_USER=minio_access_key
      - MINIO_ROOT_PASSWORD=minio_secret_key
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "minio_data:/data"

  create_default_minio_bucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set techmely_minio http://minio:9000 minio_access_key minio_secret_key;
      /usr/bin/mc mb techmely_minio/techmely;
      /usr/bin/mc mc anonymous set public techmely_minio/techmely;
      exit 0;
      "
volumes:
  postgresql_data: {}
  minio_data: {}
