name: techmely_mobile

packages:
  - lib/**
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    exec: flutter analyze .
  outdated:
    exec: flutter pub outdated
  test:
    exec: flutter test
  coverage:
    exec: flutter test --coverage
    select-package:
      dir-exists:
        - test
  generate-report:
    exec: genhtml coverage/lcov.info -o coverage/html
    select-package:
      dir-exists:
        - test
  run:mobile: melos exec --scope="mobile" -- flutter run
