name: techmely_mobile

packages:
  - lib/**
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    exec: flutter analyze .
  outdated:
    exec: flutter pub outdated
  test:
    exec: flutter test
  coverage:
    run: flutter test --coverage && genhtml coverage/lcov.info -o coverage/html
    exec:
      failFast: false
    select-package:
      dir-exists:
        - test
  run:mobile: melos exec --scope="mobile" -- flutter run
