$schema: "https://moonrepo.dev/schemas/tasks.json"

implicitInputs:
  - "package.json"

fileGroups:
  configs:
    - "*.{js,json,yml,yaml}"
  sources:
    - "src/**/*"
    - "typings/**/*.ts"
  tests:
    - "src/**/*.test.mts"
    - "tests/**/*.test.mts"
    - "tests/**/*.stories.*"
    - "**/__tests__/**/*"

tasks:
  clean:
    command:
      - "rm -rf dist"
    options:
      shell: true

  lint-biome:
    command:
      - "bunx @biomejs/biome check . --apply"
  lint-circular:
    command:
      - "madge"
  lint-typecheck:
    command: "tsc"
    args: "--noEmit"
    inputs:
      - "@globs(sources)"
      - "@globs(tests)"
      - "tsconfig.json"
      - "tsconfig.*.json"
      - "/tsconfig.base.json"

  lint:
    command: "noop"
    deps:
      - lint-biome
      - lint-circular
      - lint-typecheck

  test:
    command:
      - "vitest"
    args: "run --passWithNoTests --isolate"
    inputs:
      - "@globs(sources)"
      - "@globs(tests)"
      - "vitest.config.*"

  upgrade.deps:
    command: "npm-check-updates --dep dev,prod,peer -u -x react -x react-dom -x @types/react -x @types/react-dom"
    options:
      allowFailure: true
