[tasks.pub_get]
script = ["""
  cd apps/mobile
  flutter clean
  flutter pub get
  cd ../..
  """]
script_runner = "@shell"

[tasks.flutter-build-ios]
script = ["""
    cd apps/mobile
    flutter pub get
    flutter build ipa --split-debug-info=./ --obfuscate --verbose
    """]
script_runner = "@shell"

[tasks.flutter-build-android]
script = ["""
  cd apps/mobile
  flutter pub get
  flutter build apk --split-per-abi --split-debug-info=./ --obfuscate --verbose
 """]
script_runner = "@shell"

[tasks.flutter-build]
run_task = { name = ["flutter-build-ios", "flutter-build-android"] }
script_runner = "@shell"
