[tasks.lint.ts.format]
script = ["""
    bunx @biomejs/biome check . --apply
    """]
script_runner = "@shell"

[tasks.lint.ts.circular]
script = ["""
    bunx @biomejs/biome check . --apply
    """]
script_runner = "@shell"

[tasks.lint.ts.typecheck]
script = ["""
    bunx @biomejs/biome check . --apply
    """]
script_runner = "@shell"

[tasks.lint.ts.useless]
script = ["""
    bunx @biomejs/biome check . --apply
    """]
script_runner = "@shell"

[tasks.lint.ts]
run_task = { name = [
  "lint.ts.format",
  "lint.ts.circular",
  "lint.ts.typecheck",
  "lint.ts.useless",
] }
script_runner = "@shell"
