name: CI Mobile Workflow

on:
  push:
    paths:
      - "apps/mobile/**"
      - ".github/workflows/ci.mobile.yaml"
    branches:
      - "dev"
      - "release/*"

  pull_request:
    paths:
      - "apps/mobile/**"
      - ".github/workflows/ci.mobile.yaml"
    branches:
      - "dev"
      - "release/*"

env:
  FLUTTER_VERSION: "3.19.6"

jobs:
  prepare-linux:
    if: github.event.pull_request.draft != true
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            flutter_profile: development-linux-x86_64
            target: x86_64-unknown-linux-gnu
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

  unit_test:
    defaults:
      run:
        working-directory: apps/mobile/packages
    needs: [prepare-linux]
    if: github.event.pull_request.draft != true
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            flutter_profile: development-linux-x86_64
            target: x86_64-unknown-linux-gnu
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install flutter
        id: flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: "Run flutter pub get"
        run: flutter pub get

      - name: "Run flutter unit test"
        run: flutter test
