name: CI Mobile Workflow

on:
  push:
    paths:
      - "apps/mobile/**"
      - ".github/workflows/ci.mobile.yml"
    branches: ["dev", "release/*"]
  pull_request:
    branches: ["dev", "release/*"]

jobs:
  prepare-linux:
    if: github.event.pull_request.draft != true
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            flutter_profile: development-linux-x86_64
            target: x86_64-unknown-linux-gnu
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

  unit_test:
    needs: [prepare-linux]
    if: github.event.pull_request.draft != true
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            flutter_profile: development-linux-x86_64
            target: x86_64-unknown-linux-gnu
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true

      - name: Install flutter
        id: flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
      - name: Install need deps
        run: |
          dart pub global activate melos

      - name: "Flutter pub get"
        run: moon ci :install --query "projectName=mobile"

      - name: "Run unit test"
        run: moon ci --color --log debug :test --query "projectName=mobile"
