name: Flutter test build

on:
  push:
    paths:
    - 'apps/mobile/**'
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    name: Pub get and build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/mobile
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
      - run: flutter pub get
      - run: flutter build apk
  test:
    name: testing packages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/mobile/packages
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
      - run: flutter test 

  # code-coverage:
  #   name: coverage packages
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: apps/mobile/packages
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-java@v3
  #       with:
  #         java-version: '17'
  #         distribution: 'temurin'
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: '3.19.6'
  #     - run: flutter test --coverage

  #     - name: Setup LCOV
  #       uses: hrishikesh-kadam/setup-lcov@v1

  #     - name: Report Code Coverage
  #       uses: zgosalvez/github-actions-report-lcov@v3
  #       with:
  #         coverage-files: coverage/lcov.*.info
  #         minimum-coverage: 90
  #         artifact-name: code-coverage-report
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         update-comment: true

